Repository felddy/foundryvtt-docker, pull requests merged in 2022-09, with the labels that each got.

#426 Bump FoundryVTT version to 10.284
  Dockerfile
  README.md
  docker-compose.yml
  src/_version.py
Labels: enhancement :sparkles:, upstream :eyes:

#432 Fix the static file compression parameter name
  src/set_options.ts
Labels: bug :bug:, javascript :coffee:

#435 Fix v10 static files compress
  src/set_options.ts
Labels: bug :bug:, javascript :coffee:

#436 Bump FoundryVTT version to 10.285
  Dockerfile
  README.md
  docker-compose.yml
  src/_version.py
Labels: enhancement :sparkles:, upstream :eyes:

#440 Add regression label
  .github/labels.yml
Labels: enhancement :sparkles:

#441 Convert issue templates to forms
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/regression.md
  .github/ISSUE_TEMPLATE/regression.yml
Labels: enhancement :sparkles:

#444 Add workflow to label and close stale issues
  .github/workflows/stale-issues.yml
Labels: enhancement :sparkles:

#445 Bump FoundryVTT version to 10.286
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/regression.yml
  Dockerfile
  README.md
  docker-compose.yml
  src/_version.py
Labels: enhancement :sparkles:, upstream :eyes:

#449 Update fetch license script to handle new page elements
  src/get_license.ts
Labels: bug :bug:, javascript :coffee:

#450 Bump container version to 10.286.1
  README.md
  src/_version.py
Labels: enhancement :sparkles:
