Repository felddy/foundryvtt-docker, pull requests merged in 2023-09, with the labels that each got.

#770 Add version tag comments to each sha-pinned use in workflows
  .github/workflows/_config.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-pytest-image.yml
  .github/workflows/scorecards.yml
  .github/workflows/stale-issues.yml
  .github/workflows/sync-labels.yml
Labels: automerge :bell:, documentation :memo:, github-actions :octocat:

#795 Remove s390x from architecture list
  .github/workflows/_config.yml
  README.md
Labels: automerge :bell:, upstream :eyes:, docker :whale:, javascript :coffee:, regression :boom:

#788 Bump FoundryVTT version to 11.309
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/regression.yml
  Dockerfile
  README.md
  docker-compose.yml
  src/_version.py
Labels: documentation :memo:, upstream :eyes:, docker :whale:, regression :boom:

#797 Bump FoundryVTT version to 11.311
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/regression.yml
  Dockerfile
  README.md
  docker-compose.yml
  src/_version.py
Labels: dependencies :game_die:, documentation :memo:, enhancement :sparkles:, upstream :eyes:

#789 add CSS Theme Selection environment variable
  README.md
  src/set_options.ts
Labels: documentation :memo:, enhancement :sparkles:

#800 Blessed version of PR 789
  README.md
  src/set_options.ts
Labels: documentation :memo:, enhancement :sparkles:
