Repository felddy/foundryvtt-docker, pull requests merged in 2025-08, with the labels that each got.

#1256 Bump FoundryVTT version to 13.347
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/regression.yml
  Dockerfile
  README.md
  compose.yml
  src/version.txt
Labels: documentation :memo:, enhancement :sparkles:, upstream :eyes:

#1258 Fix Javascript cookie library errors
  .pre-commit-config.yaml
  package-lock.json
  package.json
  src/authenticate.ts
  src/get_license.ts
  src/get_release_url.ts
Labels: bug :bug:, javascript :coffee:

#1267 Fix default value for FOUNDRY_COMPRESS_WEBSOCKET
  README.md
Labels: automerge :bell:, bug :bug:, documentation :memo:

#1269 Store healthcheck cookiejar in /tmp/
  src/check_health.sh
Labels: bug :bug:

#1272 Bump FoundryVTT version to 13.348
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/regression.yml
  Dockerfile
  README.md
  compose.yml
  src/version.txt
Labels: documentation :memo:, upstream :eyes:
